import React from "react";
import styles from "./index.module.scss"
import Head from "next/head";
import Header from "../Header";
import Footer from "../Footer";
import Sidebar from "../Sidebar";

interface Props {
  children: React.ReactNode,
  className?: string,
  metaTitle?: string,
  metaDescription?: string
}

const Layout:React.FC<Props> = (
  {
    children,
    className,
    metaTitle,
    metaDescription
  }) => {
  return (
    <>
      <Head>
        <title>{metaTitle ?? "Create Next App"}</title>
        <meta name="description" content={metaDescription ?? "Generated by create next app"} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout} data-testid="Layout">
        <Header />
        <Sidebar/>
        <main>
          {children}
        </main>
        <Footer/>
      </div>
    </>
  )
}

export default Layout